//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShadowEye.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShadowEye.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Camera に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraTabHeader {
            get {
                return ResourceManager.GetString("CameraTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract Channel... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChannelExtractionMenu {
            get {
                return ResourceManager.GetString("ChannelExtractionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Integrate Channels... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChannelIntegrationMenu {
            get {
                return ResourceManager.GetString("ChannelIntegrationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert Color... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorConversionMenu {
            get {
                return ResourceManager.GetString("ColorConversionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Image Processing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageProcessingMenu {
            get {
                return ResourceManager.GetString("ImageProcessingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subtract... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageSubtraction {
            get {
                return ResourceManager.GetString("ImageSubtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputCamera {
            get {
                return ResourceManager.GetString("InputCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputFile {
            get {
                return ResourceManager.GetString("InputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ScreenShot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputScreenShot {
            get {
                return ResourceManager.GetString("InputScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiply... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MultiplicationMenu {
            get {
                return ResourceManager.GetString("MultiplicationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scale... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScalingMenu {
            get {
                return ResourceManager.GetString("ScalingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Threshold... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThresholdingMenu {
            get {
                return ResourceManager.GetString("ThresholdingMenu", resourceCulture);
            }
        }
    }
}
