//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShadowEye.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_Localization_Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Localization_Labels() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShadowEye.Properties.Resource.Localization.Labels", typeof(Resource_Localization_Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Channel Extraction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChannelExtractionDialogTitle {
            get {
                return ResourceManager.GetString("ChannelExtractionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Integrate Channels に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChannelIntegrationDialogTitle {
            get {
                return ResourceManager.GetString("ChannelIntegrationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normalize to that maximum value become maximum value of pixel format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChannelIntegrationNormalize {
            get {
                return ResourceManager.GetString("ChannelIntegrationNormalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output MatType: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChannelIntegrationOutputType {
            get {
                return ResourceManager.GetString("ChannelIntegrationOutputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color Conversion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorConversion {
            get {
                return ResourceManager.GetString("ColorConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color Conversion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorConversionDialogTitle {
            get {
                return ResourceManager.GetString("ColorConversionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conversion Type: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorConversionType {
            get {
                return ResourceManager.GetString("ColorConversionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComputeButton {
            get {
                return ResourceManager.GetString("ComputeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Height: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bit depth に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageInfoBits {
            get {
                return ResourceManager.GetString("ImageInfoBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Channels に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageInfoChannels {
            get {
                return ResourceManager.GetString("ImageInfoChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageInfoColorMode {
            get {
                return ResourceManager.GetString("ImageInfoColorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageInfoTitle {
            get {
                return ResourceManager.GetString("ImageInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputLeft {
            get {
                return ResourceManager.GetString("InputLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputRight {
            get {
                return ResourceManager.GetString("InputRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keep aspect ratio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeepAspectRatio {
            get {
                return ResourceManager.GetString("KeepAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Channel 0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelChannel0 {
            get {
                return ResourceManager.GetString("LabelChannel0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Channel 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelChannel1 {
            get {
                return ResourceManager.GetString("LabelChannel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Channel 2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelChannel2 {
            get {
                return ResourceManager.GetString("LabelChannel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Channel 3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelChannel3 {
            get {
                return ResourceManager.GetString("LabelChannel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelTarget {
            get {
                return ResourceManager.GetString("LabelTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiplication に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MultiplicationDialogTitle {
            get {
                return ResourceManager.GetString("MultiplicationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NotSupportFormat Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotSupportFormatError {
            get {
                return ResourceManager.GetString("NotSupportFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output Format: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OutputFormat {
            get {
                return ResourceManager.GetString("OutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Percent に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pixel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pixel {
            get {
                return ResourceManager.GetString("Pixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preview に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return original size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReturnOriginalSize {
            get {
                return ResourceManager.GetString("ReturnOriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveDialogOpenText {
            get {
                return ResourceManager.GetString("SaveDialogOpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scale Factor: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScaleFactor {
            get {
                return ResourceManager.GetString("ScaleFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scaling に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScalingDialogTitle {
            get {
                return ResourceManager.GetString("ScalingDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capturing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScreenShotCapturing {
            get {
                return ResourceManager.GetString("ScreenShotCapturing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Film に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScreenShotCapturingFilm {
            get {
                return ResourceManager.GetString("ScreenShotCapturingFilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moving Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScreenShotCapturingMoving {
            get {
                return ResourceManager.GetString("ScreenShotCapturingMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Still Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScreenShotCapturingStill {
            get {
                return ResourceManager.GetString("ScreenShotCapturingStill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Screen Shot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScreenShotDialogTitle {
            get {
                return ResourceManager.GetString("ScreenShotDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preview に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScreenShotPreview {
            get {
                return ResourceManager.GetString("ScreenShotPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shoot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScreenShotShootButton {
            get {
                return ResourceManager.GetString("ScreenShotShootButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ScreenShot Target に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScreenShotTarget {
            get {
                return ResourceManager.GetString("ScreenShotTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScreenShotTargetDesktop {
            get {
                return ResourceManager.GetString("ScreenShotTargetDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entire Virtual Screen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScreenShotTargetEntireVirtualScreen {
            get {
                return ResourceManager.GetString("ScreenShotTargetEntireVirtualScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Screen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScreenShotTargetScreen {
            get {
                return ResourceManager.GetString("ScreenShotTargetScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Screen: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScreenShotTargetScreenLabel {
            get {
                return ResourceManager.GetString("ScreenShotTargetScreenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScreenShotTargetWindow {
            get {
                return ResourceManager.GetString("ScreenShotTargetWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only client area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScreenShotTargetWindowOnlyClientArea {
            get {
                return ResourceManager.GetString("ScreenShotTargetWindowOnlyClientArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScreenShotTargetWindowProcessLabel {
            get {
                return ResourceManager.GetString("ScreenShotTargetWindowProcessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select camera device: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectCameraDialogText {
            get {
                return ResourceManager.GetString("SelectCameraDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select camera device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectCameraDialogTitle {
            get {
                return ResourceManager.GetString("SelectCameraDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subtract Absolutely に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubtractAbsolute {
            get {
                return ResourceManager.GetString("SubtractAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subtraction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubtractionDialogTitle {
            get {
                return ResourceManager.GetString("SubtractionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Average に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubWorkbenchHistogramAverage {
            get {
                return ResourceManager.GetString("SubWorkbenchHistogramAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubWorkbenchHistogramFps {
            get {
                return ResourceManager.GetString("SubWorkbenchHistogramFps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubWorkbenchHistogramHeight {
            get {
                return ResourceManager.GetString("SubWorkbenchHistogramHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Median に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubWorkbenchHistogramMedian {
            get {
                return ResourceManager.GetString("SubWorkbenchHistogramMedian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pixels に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubWorkbenchHistogramPixels {
            get {
                return ResourceManager.GetString("SubWorkbenchHistogramPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Standard Deviation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubWorkbenchHistogramStandardDeviation {
            get {
                return ResourceManager.GetString("SubWorkbenchHistogramStandardDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Histogram に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubWorkbenchHistogramTabHeader {
            get {
                return ResourceManager.GetString("SubWorkbenchHistogramTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubWorkbenchHistogramType {
            get {
                return ResourceManager.GetString("SubWorkbenchHistogramType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubWorkbenchHistogramWidth {
            get {
                return ResourceManager.GetString("SubWorkbenchHistogramWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TargetImage {
            get {
                return ResourceManager.GetString("TargetImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target Image Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TargetImageInformation {
            get {
                return ResourceManager.GetString("TargetImageInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thresholding に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Thresholding {
            get {
                return ResourceManager.GetString("Thresholding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max Value: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThresholdingMaxValue {
            get {
                return ResourceManager.GetString("ThresholdingMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Threshold Type: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThresholdingMethod {
            get {
                return ResourceManager.GetString("ThresholdingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Threshold Value: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThresholdValue {
            get {
                return ResourceManager.GetString("ThresholdValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Width: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
